### ISSUE TITLE
Fusing text with background in dropdown list items in dashboard UI

### ISSUE THREAD

**Issue by alexander-mart** [terminusdb/terminusdb-dashboard#309]
**Describe the bug**
Fusing text with background in dropdown list items in dashboard UI

**To Reproduce**
—

**Expected behavior**
Acceptable contrast ratio passed by devtools:
https://developer.chrome.com/docs/devtools/accessibility/contrast

**Screenshots**
![image](https://github.com/terminusdb/terminusdb/assets/14993551/8bc46094-e21e-43fd-89ef-fd79f86f67d8)

**Info (please complete the following information):**
- Cloud-version

**Additional context**
Please find an interface specialist to join your team. If the product has already reached a stage where it needs to grow in the number of users, the interface is not a secondary element, but an important part of the product. Basic UI review would not allow the bug indicated in the example to pass into production.

Also I recommend to use [TailwindCSS](https://tailwindcss.com/) instead of played-out Bootstrap

**Comment by alexander-mart** [comment]
Temporary fix with [stylebot.dev](https://stylebot.dev/):

```css
/* https://github.com/terminusdb/terminusdb-dashboard/pull/310 */
.form-control {
    color: #fff !important;
    background-color: #000 !important;
}
```
